#!/bin/bash
set -euo pipefail

echo "╔═══════════════════════════════════════════╗"
echo "║   LLM Observability Stack — Setup         ║"
echo "╚═══════════════════════════════════════════╝"
echo ""
echo "This will generate .env and keys.jsonc files."
echo ""

# ── Defaults ──
NETWORK_NAME="llm-proxy-net"
COMPOSE_PROJECT_NAME="agent-super-spy"
OTEL_PROJECT_NAME="llm-proxy"
TRACE_EXPORTERS="phoenix"
LLM_PROXY_PORT="4000"
MITMPROXY_UI_PORT="8081"
MITMPROXY_WEB_PASSWORD="mitmpass"

# ── Network & Docker ──
read -rp "Docker network name [$NETWORK_NAME]: " input
NETWORK_NAME="${input:-$NETWORK_NAME}"

read -rp "Compose project name [$COMPOSE_PROJECT_NAME]: " input
COMPOSE_PROJECT_NAME="${input:-$COMPOSE_PROJECT_NAME}"

# ── LLM Proxy ──
echo ""
echo "Select OTEL backend:"
echo "  1. Phoenix"
echo "  2. Opik"
echo "  3. Both"
read -rp "Choice [1]: " input
case "${input:-1}" in
  1) TRACE_EXPORTERS="phoenix" ;;
  2) TRACE_EXPORTERS="opik" ;;
  3) TRACE_EXPORTERS="phoenix,opik" ;;
  *)
    echo "Invalid choice: ${input}. Expected 1, 2, or 3."
    exit 1
    ;;
esac

read -rp "OTEL project name [$OTEL_PROJECT_NAME]: " input
OTEL_PROJECT_NAME="${input:-$OTEL_PROJECT_NAME}"

read -rp "LLM proxy port [$LLM_PROXY_PORT]: " input
LLM_PROXY_PORT="${input:-$LLM_PROXY_PORT}"

# ── mitmproxy ──
read -rp "mitmproxy UI port [$MITMPROXY_UI_PORT]: " input
MITMPROXY_UI_PORT="${input:-$MITMPROXY_UI_PORT}"

read -rp "mitmproxy web password [$MITMPROXY_WEB_PASSWORD]: " input
MITMPROXY_WEB_PASSWORD="${input:-$MITMPROXY_WEB_PASSWORD}"

# ── Optional Claude services ──
echo ""
echo "Optional Claude services:"
PROFILES=""

if [[ "$TRACE_EXPORTERS" == *"phoenix"* ]]; then
  PROFILES="phoenix"
fi

read -rp "  Enable Claude chat UI? [y/N]: " input
[[ "$input" == [yY] ]] && PROFILES="${PROFILES:+$PROFILES,}claude-chat"

read -rp "  Enable Claude API proxy? [y/N]: " input
[[ "$input" == [yY] ]] && PROFILES="${PROFILES:+$PROFILES,}claude-proxy"

read -rp "  Enable Claude Code CLI? [y/N]: " input
[[ "$input" == [yY] ]] && PROFILES="${PROFILES:+$PROFILES,}claude-code"

# ── API Keys (for optional Claude services) ──
ANTHROPIC_API_KEY=""
if [[ ",${PROFILES}," == *",claude-chat,"* || ",${PROFILES}," == *",claude-proxy,"* || ",${PROFILES}," == *",claude-code,"* ]]; then
  echo ""
  echo "Claude services need an Anthropic API key (or place credentials.json in data/claude/):"
  read -rp "  Anthropic API key (Enter to skip): " ANTHROPIC_API_KEY
fi

# ── Key config for llm-proxy ──
echo ""
echo "LLM Proxy key configuration:"
echo "  Clients send a local API key to llm-proxy, which swaps it for the real provider key."
echo ""

LOCAL_KEY=""
ANTHROPIC_PROVIDER_KEY=""
OPENAI_PROVIDER_KEY=""
OPENROUTER_PROVIDER_KEY=""

read -rp "  Local API key (what clients will send — Enter to skip, edit keys.jsonc later): " LOCAL_KEY

if [[ -n "$LOCAL_KEY" ]]; then
  read -rp "    Anthropic key for this local key: " ANTHROPIC_PROVIDER_KEY
  read -rp "    OpenAI key for this local key: " OPENAI_PROVIDER_KEY
  read -rp "    OpenRouter key for this local key (Enter to skip): " OPENROUTER_PROVIDER_KEY
fi

# ── Write .env ──
{
  echo "# LLM Observability Stack — generated by setup.sh"
  echo ""
  echo "# Docker"
  echo "COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}"
  echo "NETWORK_NAME=${NETWORK_NAME}"
  echo ""
  echo "# LLM Proxy"
  echo "LLM_PROXY_PORT=${LLM_PROXY_PORT}"
  echo "TRACE_EXPORTERS=${TRACE_EXPORTERS}"
  echo "OTEL_PROJECT_NAME=${OTEL_PROJECT_NAME}"
  echo "# OPIK_OTEL_ENDPOINT=http://opik-frontend:5173/api/v1/private/otel/v1/traces"
  echo "# OPIK_API_KEY="
  echo "# OPIK_WORKSPACE="
  echo "# OPIK_OTEL_HEADERS="
  echo "# PHOENIX_COLLECTOR_ENDPOINT=http://phoenix:6006"
  echo "# PHOENIX_API_KEY="
  echo "# PHOENIX_OTEL_HEADERS="
  echo ""
  echo "# mitmproxy"
  echo "MITMPROXY_UI_PORT=${MITMPROXY_UI_PORT}"
  echo "MITMPROXY_WEB_PASSWORD=${MITMPROXY_WEB_PASSWORD}"
  echo ""
  echo "# Optional services (comma-separated: phoenix,claude-chat,claude-proxy,claude-code)"
  if [[ -n "$PROFILES" ]]; then
    echo "COMPOSE_PROFILES=${PROFILES}"
  else
    echo "# COMPOSE_PROFILES=phoenix,claude-chat,claude-proxy,claude-code"
  fi
  echo ""
  echo "# Anthropic API key (for optional Claude services)"
  if [[ -n "$ANTHROPIC_API_KEY" ]]; then
    echo "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}"
  else
    echo "# ANTHROPIC_API_KEY="
  fi
  echo ""
  echo "OPIK_USAGE_REPORT_ENABLED=false"
} > .env

echo ""
echo "==> .env written"

# ── Write keys.jsonc ──
if [[ -n "$LOCAL_KEY" ]]; then
  ENTRIES=()
  [[ -n "$ANTHROPIC_PROVIDER_KEY" ]] && ENTRIES+=("    \"anthropic\": \"${ANTHROPIC_PROVIDER_KEY}\"")
  [[ -n "$OPENAI_PROVIDER_KEY" ]] && ENTRIES+=("    \"openai\": \"${OPENAI_PROVIDER_KEY}\"")
  [[ -n "$OPENROUTER_PROVIDER_KEY" ]] && ENTRIES+=("    \"api.openrouter.com\": \"${OPENROUTER_PROVIDER_KEY}\"")

  if [[ ${#ENTRIES[@]} -eq 0 ]]; then
    echo "  WARNING: No provider keys entered for local key '${LOCAL_KEY}'. Skipping keys.jsonc."
    echo "  Edit keys.jsonc manually to add provider keys."
  else
    {
      echo "{"
      echo "  \"${LOCAL_KEY}\": {"
      # Print entries with commas between (no trailing comma for valid JSON)
      for i in "${!ENTRIES[@]}"; do
        if [[ $i -lt $((${#ENTRIES[@]} - 1)) ]]; then
          echo "${ENTRIES[$i]},"
        else
          echo "${ENTRIES[$i]}"
        fi
      done
      echo "  }"
      echo "}"
    } > keys.jsonc
    echo "==> keys.jsonc written"
  fi
elif [[ ! -f keys.jsonc ]]; then
  cp keys.jsonc.example keys.jsonc
  echo "==> keys.jsonc.example copied to keys.jsonc (edit to add your keys)"
fi

echo ""
echo "Setup complete! Run ./start.sh to start the stack."
echo ""
echo "URLs (after starting):"
echo "  LLM Proxy:    http://localhost:${LLM_PROXY_PORT}"
echo "  mitmproxy UI: http://localhost:${MITMPROXY_UI_PORT}/?token=${MITMPROXY_WEB_PASSWORD}"
if [[ "$TRACE_EXPORTERS" == *"opik"* ]]; then
  echo "  Opik UI:      http://localhost:5173"
fi
if [[ "$TRACE_EXPORTERS" == *"phoenix"* ]]; then
  echo "  Phoenix UI:   http://localhost:6006"
fi
echo ""
echo "Configure your SDKs:"
echo "  ANTHROPIC_BASE_URL=http://localhost:${LLM_PROXY_PORT}/anthropic"
echo "  OPENAI_BASE_URL=http://localhost:${LLM_PROXY_PORT}/openai"
echo "  Generic:      http://localhost:${LLM_PROXY_PORT}/<hostname>/path"
